#!/usr/bin/env sh
set -eu

BIN=${BIN:-/mnt/data/sample_vi_hand_gesture}
DET_MODEL=${DET_MODEL:-/mnt/data/yolov8n_det_hand_384_640_INT8_cv181x.cvimodel}
KPT_MODEL=${KPT_MODEL:-/mnt/data/keypoint_hand_128_128_INT8_cv181x.cvimodel}
CLS_MODEL=${CLS_MODEL:-/mnt/data/cls_keypoint_hand_gesture_1_42_INT8_cv181x.cvimodel}

export SAMPLE_TDL_VPSS_DEV=${SAMPLE_TDL_VPSS_DEV:-0}
export SAMPLE_TDL_VPSS_PROBE_DELAY_MS=${SAMPLE_TDL_VPSS_PROBE_DELAY_MS:-600}
export SAMPLE_TDL_VPSS_PROBE_TIMEOUT_MS=${SAMPLE_TDL_VPSS_PROBE_TIMEOUT_MS:-1200}
export SAMPLE_TDL_VPSS_PROBE_RETRIES=${SAMPLE_TDL_VPSS_PROBE_RETRIES:-6}
export SAMPLE_TDL_VI_BIND_CHN=${SAMPLE_TDL_VI_BIND_CHN:-0}
export SAMPLE_TDL_VPSS_MODE=${SAMPLE_TDL_VPSS_MODE:-dual}
export SAMPLE_TDL_VPSS_INPUT_PROFILE=${SAMPLE_TDL_VPSS_INPUT_PROFILE:-mem_isp}

echo "Run: $BIN"
echo "VPSS_DEV=$SAMPLE_TDL_VPSS_DEV MODE=$SAMPLE_TDL_VPSS_MODE PROFILE=$SAMPLE_TDL_VPSS_INPUT_PROFILE"
exec "$BIN" "$DET_MODEL" "$KPT_MODEL" "$CLS_MODEL"
